apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificaiton
  labels:
    app: notificaiton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificaiton
  template:
    metadata:
      labels:
        app: notificaiton
    spec:
      containers:
        - name: notificaiton
          image: username/notificaiton:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5